export const ProjectData = 
[
  {
    image: '/work/1.png',
    category: 'react js',
    name: 'Clodeo Web App',
    description: 'Pembuatan aplikasi berbasis web menggunakan Framework React JS untuk keperluan membantu UMKM membuat pembukuan secara online dan mudah.',
    link: 'https://clodeo.com/',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/2.png',
    category: 'next js',
    name: 'Shipdeo Web App',
    description: 'Pembuatan aplikasi berbasis web menggunakan Framework React JS untuk keperluan membantu masyarakat dalam pengiriman barang',
    link: 'https://shipdeo.com/',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/3.png',
    category: 'next js',
    name: 'GajiCermar Web Panel',
    description: 'Pembuatan aplikasi berbasis web menggunakan Framework React JS untuk keperluan membantu HRD dalam mengelola pembayaran gaji dan mengelola absensi karyawan.',
    link: 'https://www.gajicermat.com/',
    isLatest: true,
    github: '/'
  },
  {
    image: '/work/3.png',
    category: 'next js',
    name: 'Omcermat Web Panel',
    description: 'Pembuatan aplikasi berbasis web menggunakan Framework React JS untuk keperluan membantu HRD dalam mengelola pembayaran gaji dan mengelola absensi karyawan. berbasis lite',
    link: 'https://www.gajicermat.com/',
    github: '/',
    isLatest: true,
  },
  {
    image: '/work/4.png',
    category: 'next js',
    name: 'PeopleNote Web',
    description: 'Pembuatan aplikasi berbasis web menggunakan Framework React JS untuk keperluan membantu HRD dalam mengelola pembayaran gaji dan mengelola absensi karyawan. Dengan UI dan UX yang lebih modern.',
    link: 'https://www.gajicermat.com/',
    github: '/',
    isLatest: true,
  },
  {
    image: '/work/5.png',
    category: 'react native',
    name: 'Clodeo Mobile',
    description: 'Pembuatan aplikasi berbasis Android dan IOS menggunakan Framework React Native untuk keperluan membantu pengelolaan marketplace dengan mudah.',
    link: 'https://play.google.com/store/search?q=clodeo&c=apps&hl=en-ID',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/6.png',
    category: 'react native',
    name: 'Kantin Clodeo Mobile',
    description: 'Pembuatan aplikasi berbasis Android dan IOS menggunakan Framework React Native untuk keperluan membantu karyawan membeli keperluan sehari-hari.',
    link: 'https://play.google.com/store/apps/details?id=com.kantin_clodeo&hl=en-ID',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/7.png',
    category: 'react native',
    name: 'Koperasi SiCepat Mobile',
    description: 'Pembuatan aplikasi berbasis Android dan IOS menggunakan Framework React Native untuk keperluan membantu karyawan membeli keperluan sehari-hari.',
    link: '/',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/8.png',
    category: 'react native',
    name: 'Shipdeo Mobile App',
    description: 'Pembuatan aplikasi berbasis Android dan IOS menggunakan Framework React Native untuk keperluan membantu masyarakat dalam pengiriman barang dengan mudah.',
    link: 'https://play.google.com/store/apps/details?id=com.shipdeo&hl=en-ID',
    github: '/',
    isLatest: false,
  },
  {
    image: '/work/9.png',
    category: 'react native',
    name: 'KerjaCermat',
    description: 'Pembuatan aplikasi berbasis Android dan IOS menggunakan Framework React Native untuk keperluan membantu karyawan untuk melakukan absensi dan mengakses berbagai info lainnya.',
    link: 'https://play.google.com/store/apps/details?id=com.uangcermat.kerjacermatess&hl=en-ID',
    github: '/',
    isLatest: true,
  },
  {
    image: '/work/10.png',
    category: 'photo',
    name: 'Street Photography',
    description: 'Pengambilan photo random yang dibalut dengan sedikit sentuhan cinematic supaya terlihat indah.',
    link: 'https://unsplash.com/@mika0521/',
    github: '/',
    instagram: 'https://www.instagram.com/mika.photography5/',
    isLatest: true,
  },
]